"""DeskPilot assets module."""
from .illustrations import (
    get_feature_icons,
    get_logo_svg,
    get_loading_dots,
    get_empty_state,
    get_icon,
    LOGO_SVG,
    ACTIONS_SVG,
    LAUNCHERS_SVG,
    TEMPLATES_SVG,
    MACROS_SVG,
    SETTINGS_SVG,
    TEST_SVG,
    SUCCESS_SVG,
    ERROR_SVG,
    FLOW_SVG,
    SCHEDULE_SVG,
    PLAY_SVG,
    STOP_SVG,
)

__all__ = [
    "get_feature_icons",
    "get_logo_svg", 
    "get_loading_dots",
    "get_empty_state",
    "get_icon",
    "LOGO_SVG",
    "ACTIONS_SVG",
    "LAUNCHERS_SVG",
    "TEMPLATES_SVG",
    "MACROS_SVG",
    "SETTINGS_SVG",
    "TEST_SVG",
    "SUCCESS_SVG",
    "ERROR_SVG",
    "FLOW_SVG",
    "SCHEDULE_SVG",
    "PLAY_SVG",
    "STOP_SVG",
]
